name: Tablist
api-version: '1.15'
version: "1.5.1"
autor: Seine_Eloquenz
main: de.seine_eloquenz.tablist.tablist
commands:
   tablist:
      description: This is the main Tablist command.
      aliases: [tlist, tl]
softdepend: [PlaceholderAPI]